// "use client";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import Header from "./components/Navbar";
import { Suspense, useEffect, useState } from "react";
import Loading from "./loading";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const customFont = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agency Creative",
  description: "Generated by create next app",
  icons: {
    icon: "./images/logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [isLoading, setIsLoading] = useState(true);
  // useEffect(() => {
  //   const timer = setTimeout(() => {
  //     setIsLoading(false);
  //   }, 3000);
  //   return () => clearTimeout(timer);
  // });

  return (
    <html lang="en">
      <body className={customFont.className}>
        {/* <>
          {isLoading ? (
            <LoadingScreen />
          ) : (
            <>
              <Header />
              {children}
            </>
          )}
        </> */}
        <Suspense fallback={<Loading />}>
          <Navbar />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
