// import type { Metadata } from "next";
"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Sections/Navbar";
import { Suspense, useEffect, useState } from "react";
import Loading from "./loading";
import Navbar from "./components/Sections/Navbar";
import Footer from "./components/Sections/Footer";
import useLoading from "./hooks/useLoading";

const customFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "NOS Digital Solutions",
//   description: "Generated by create next app",
//   icons: {
//     icon: "./images/logo.png",
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const loading = useLoading(500);

  return (
    <html lang="en">
      <body className={customFont.className}>
        <Suspense fallback={<Loading />}>
          {loading ? (
            <Loading />
          ) : (
            <>
              <Navbar />
              {children}
              <Footer />
            </>
          )}
        </Suspense>
      </body>
    </html>
  );
}
